### ISSUE TITLE
conda version of fitgrid is outdated and does not match the tutorial

### ISSUE THREAD

**Issue by astoermann** [kutaslab/fitgrid#132]
>>> fitgrid.__file__
'/home/astoermann/.conda/envs/fitgrid/lib/python3.6/site-packages/fitgrid/__init__.py'

>>> pd.read_hdf(example_filename).head(4)
                                        h5_dataset  log_evcodes  log_flags  stim_id  context_id  ...       MiOc         A2      HEOG       rle        rhz
Epoch_idx expt sub_id item_id  Time                                                              ...                                                     
0         lm1  lm01   10005_id -500  lm01/dblock_0            0          0        5           9  ... -25.812500 -11.640625  0.000000  3.310547 -13.093750
                               -496  lm01/dblock_0            0          0        5           9  ... -24.109375  -7.519531 -0.503906 -0.945801 -15.898438
                               -492  lm01/dblock_0            0          0        5           9  ... -26.546875  -8.734375 -6.296875 -7.566406 -20.109375
                               -488  lm01/dblock_0            0          0        5           9  ... -25.078125 -14.070312  0.755859 -8.515625 -17.765625

[4 rows x 44 columns]

>>> epochs = fitgrid.epochs_from_hdf(filename=example_filename, key=None, time='Time', epoch_id='Epoch_idx',channels=['lle','lhz','MiPf','LLPf','RLPf','LMPf','RMPf','LDFr','RDFr','LMFr','RMFr','LMCe','RMCe','MiCe','MiPa','LDCe','RDCe','LDPa','RDPa','LMOc','RMOc','LLTe','RLTe','LLOc','RLOc','MiOc','A2','HEOG','rle','rhz'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: epochs_from_hdf() got an unexpected keyword argument 'filename'

**Comment by andportnoy** [comment]
@astoermann Thank you! This happens because the version of fitgrid that is available through conda is slightly outdated, and I need to package a new one. I'll update it and get back to you on this.

**Comment by andportnoy** [comment]
@astoermann I updated the conda package, could you try running `conda update -c kutaslab fitgrid`? After that that error shouldn't happen.

**Comment by astoermann** [comment]
@andportnoy  Still getting it

**Comment by andportnoy** [comment]
@astoermann Did fitgrid update?

**Comment by astoermann** [comment]
(fitgrid) [astoermann@mkgpu1 fitgrid]$ conda update -c kutaslab fitgrid
Solving environment: done

'#All requested packages already installed.

**Comment by andportnoy** [comment]
@astoermann Got you, the package didn't go to `kutaslab`, it went to `aportnoy` instead... So if you run `conda update -c aportnoy fitgrid`, that should do it. In the meanwhile I'll figure out how to get it into `kutaslab`.

**Comment by andportnoy** [comment]
@astoermann Ok, it's in `kutaslab`, just for posterity:

To upload to `kutaslab`, add `-u kutaslab` to `anaconda upload`, so:
```bash
anaconda upload -u kutaslab fitgrid.tar.bz2
```

I also need to update the instructions in the wiki.

**Comment by astoermann** [comment]
This worked for me if I type line by line in python in a terminal window, but my jupyter notebook with the same code isn't working for some reason. Will have to explore tomorrow.

**Comment by andportnoy** [comment]
@astoermann Got it. You might have to restart both the notebook and the Jupyter server.

**Comment by andportnoy** [comment]
Trying to replicate this right now on MKGPU.

**Comment by andportnoy** [comment]
@astoermann Most likely this happens because Jupyter falls back to the conda base installation. So if when you type `which jupyter` you see `/usr/local/anaconda3/bin/jupyter`, you are using the base jupyter which uses whatever is installed in the base (including the older version of fitgrid).

To fix this, install jupyter in the `fitgrid` environment by running `conda install fitgrid`.

**Comment by andportnoy** [comment]
@astoermann The tutorial notebook runs fine for me after I install Jupyter in the environment.

**Comment by andportnoy** [comment]
`fitgrid` was updated and the tutorial runs fine.
