### ISSUE TITLE
travis failing ... statsmodels.OLSinfluence changed

### ISSUE THREAD

**Issue by turbach** [kutaslab/fitgrid#152]
Which trips fitgrid.utils.summary tests that guard against such changes. Likely not serious.

**Comment by andportnoy** [comment]
Statsmodels updated from `0.9.0` to `0.10.0`,

last passing build:
https://travis-ci.org/kutaslab/fitgrid/builds/553069542#L2188

current failing build:
https://travis-ci.org/kutaslab/fitgrid/builds/554479659#L2186

**Comment by turbach** [comment]
Yup ... `statsmodels 0.10.0` didn't make it onto the default anaconda channel right away. Then it did and kaboom. I'll pin fitgrid to 0.9.0 for now, I know where the issue is, have to look into the consequences for summary.py diagnostics. Could be a patch in fitgrid 0.4 if its a tweak or revision in 0.5 if it needs more work.

**Comment by turbach** [comment]
fixed it with statsmodels 0.9.0
