### ISSUE TITLE
a contributor code of conduct is needed

### ISSUE THREAD

**Issue by turbach** [kutaslab/fitgrid#163]
such as https://www.contributor-covenant.org/

**Comment by andportnoy** [comment]
@turbach I'm trying to add this on GitHub and it needs a contact email address. Can I put yours?

**Comment by turbach** [comment]
Sure ... this is a JOSS submission requirement. They link to
https://www.contributor-covenant.org/ what did you have in mind?

**Comment by andportnoy** [comment]
@turbach Yeah, I meant this specific one. Will add it in a moment.

**Comment by andportnoy** [comment]
@turbach Here it is: #170.

**Comment by turbach** [comment]
Closed by #170
