### ISSUE TITLE
fitgrid's pinned rpy2 and pymer4 have become stale

### ISSUE THREAD

**Issue by andportnoy** [kutaslab/fitgrid#169]
See #167.

**Comment by turbach** [comment]
yes, keenly aware.

**Comment by turbach** [comment]
@andportnoy Broader view ... my understanding is that Python 3.7 is the last Janus release that looks backward to 2.7 and forward to 3.X. Starting with 3.8 ties with Python 2 are abandoned entirely.

Is there any value targeting fitgrid for Python 3.7 or should it hop up to 3.8?

Either way prior to a JOSS writeup I'd propose bumping fitgrid from 0.4.X to 0.5.X for the current flavor of 3.6 (3.7?) compatible stable/maintenance releases and work toward Python 3.8 on a new minor release series.

**Comment by andportnoy** [comment]
Since main Anaconda channel tends to lag significantly, jumping to 3.8 might be harder than 3.7 (some packages might be unavailable), but I'd rather have the later version if possible.

**Comment by turbach** [comment]
A chokepoint for fitgrid was pymer4 b.c. of rpy2 and pandas. I've been discussing pymer4 updates with @ejolly and submitted a pymer4 patch (PR [#63](https://github.com/ejolly/pymer4/pull/63)) which, together with conda packaging (https://github.com/ejolly/pymer4/issues/58#issuecomment-639055888) appears to uncork Py 3.7, numpy 1.18, and pandas 1.0.3 for pymer4 in conda envs. Consequences for fitgrid TBD, I expect some patching for pandas 1.0.

**Comment by turbach** [comment]
Closed by #175
