### ISSUE TITLE
YAML "yes" -> Fitgrid 1

### ISSUE THREAD

**Issue by eprovenz** [kutaslab/fitgrid#172]
When I put this in my yaml header:
```
q1: yes
```
it ends up as a 1 in my fitgrid object.

With Tom, we inspected the data in pygarv and saw that it was labelled as "q1: True" in pygarv

**Comment by turbach** [comment]
This is expected behavior in YAML 1.1  https://yaml.org/spec/1.1/

Use quotes, "yes"  to tell YAML you want the three charcter string rather than boolean True/False 1/0. 

This behavior changes in YAML 1.2, the three characters are interpreted as a string.
