### ISSUE TITLE
memory

### ISSUE THREAD

**Issue by turbach** [kutaslab/fitgrid#49]
appears the big job swamped memory, bound to happen sooner or later

data ~12M rows x 95 columns
fitting ... lm, RHS='1 + cont'

```
[turbach@mkgpu1 ~]$ free -h
              total        used        free      shared  buff/cache   available
Mem:           440G        137G        261G        220M         42G        301G
Swap:           64G         64G         26M
[turbach@mkgpu1 ~]$
```
FitBuckets whitelisted fit attributes to scrape into the bucket.

Perhaps modeler-specific config dicts to whitelist and/or blacklist?

**Comment by andportnoy** [comment]
@turbach Hmm, that looks like normal memory usage on mkgpu to me, except for the maxed out swap... And majority of what's used is taken by my and Melissa's processes.

**Comment by andportnoy** [comment]
@turbach Looks like the switch to groupwise from channelwise processing didn't improve the memory performance.

**Comment by andportnoy** [comment]
A potential solution is to reuse the fit object as described on the mailing list: https://groups.google.com/forum/#!topic/pystatsmodels/ms1a9IftQQk

**Comment by andportnoy** [comment]
See #98.
