### ISSUE TITLE
minimal conda env

### ISSUE THREAD

**Issue by turbach** [kutaslab/fitgrid#55]
Problem: mixed effect modeling in fitgrid lives on pymer4 which lives on rpy2 and R which are version and lib picky.

Proposed solution: add a conda environment yaml file to clone a minimal environment for running FitGrid.

FitGrid installation becomes something like

```
conda env create -f fitgrid_minimal.yml -n fitgrid
source activate fitgrid
pip install fitgrid
```
Have at it ...

**Comment by andportnoy** [comment]
@turbach I would separate this into 2 progressive steps:

1. Get `pymer4`'s dependencies right, write them down in a YAML file.
2. Build a `conda` package, so you could `conda install fitgrid` and everything works.

**Comment by turbach** [comment]
agreed

**Comment by andportnoy** [comment]
@turbach I'm going to upload it to my channel for now, but do you think you could make a PyPi + Anaconda Kutas Lab account? Conda, like PyPi, has a process for ownership transfer: 
https://docs.anaconda.com/anaconda-cloud/user-guide/tasks/work-with-packages/#transferring-a-package-to-a-new-owner

**Comment by andportnoy** [comment]
This was solved by creating a `conda` package for `fitgrid`. `fitgrid` can now be installed by running

    conda install -c aportnoy fitgrid
