### ISSUE TITLE
blas threads getter and setter tests now failing on Travis

### ISSUE THREAD

**Issue by andportnoy** [kutaslab/fitgrid#86]
https://travis-ci.org/kutaslab/fitgrid/builds/464017224#L1843

**Comment by andportnoy** [comment]
`blas.get_n_threads` always returns `1`. Is [this](https://changelog.travis-ci.com/deprecation-container-based-linux-build-environment-82037) related?

**Comment by andportnoy** [comment]
`conda` should create the environment verbosely and let's also print `numpy.show_config()`.

**Comment by andportnoy** [comment]
Same tests pass on mkgpu and on my laptop.

**Comment by andportnoy** [comment]
There was a worker version bump:

Compare 
https://travis-ci.org/kutaslab/fitgrid/builds/463705553#L3
to
https://travis-ci.org/kutaslab/fitgrid/jobs/464017225#L3

**Comment by andportnoy** [comment]
This is definitely due to some extraneous changes. Here's an older (successful) build that I restarted recently: https://travis-ci.org/kutaslab/fitgrid/builds/461986881#L415. Now it fails.

**Comment by andportnoy** [comment]
These tests pass with stock Travis Python and with conda Python 3.7:
https://travis-ci.org/kutaslab/fitgrid/builds/464624502
https://travis-ci.org/kutaslab/fitgrid/builds/464629223

For now we'll skip these tests when run on Travis. We still test the context manager, so inside the context manager there is a guarantee that NumPy is single-threaded. It's just that when it's single-threaded by default, it doesn't budge.

I'll keep this issue open.

**Comment by turbach** [comment]
Closed by #87
